### ISSUE TITLE
Body display: table can be removed

### ISSUE THREAD

**Issue by acacheung** [andrealeigh/dobot#18]
Not sure what this was supposed to do. Is there a reason for this?

**Comment by andrealeigh** [comment]
On large resolution sizes my body wasn't centered. I had tried using margin: { auto; } and vertical-align: { middle; } but neither worked. I found somewhere that if you use display: { table; } with margin: { auto; } you can vertically center a body element. 

If there is another way to do this please share! Otherwise let me know when I can close this issue.

**Comment by acacheung** [comment]
Ok that's fine. Closing issue :)
