### ISSUE TITLE
Hover state of button doesn't match psd

### ISSUE THREAD

**Issue by acacheung** [andrealeigh/dobot#9]
![screen shot 2015-03-01 at 3 18 50 pm](https://cloud.githubusercontent.com/assets/1054686/6432647/5a74fb86-c026-11e4-9679-29535dfdcb4b.png)

I think you said you had a few questions about this. Let's discuss it here.

**Comment by andrealeigh** [comment]
Hey Amanda!

Yes I did have a couple of questions about this. From what I can tell in the photoshop mockup it looks like the button has the following in the hover state: Color change to #CFCEBA (a beige/tan color), a solid border color of #1BBCBF (a turquoise color), and a diagonal dotted pattern that is slightly transparent. 

I didn't know how to add the pattern using CSS -- did you want me to use a button image that would show up in the hover state instead, or is there a way to create this pattern in CSS? 

The other thing I had a question about was the "drop shadow" effect listed under Buy This Hover / Button / Effects. The last time I looked at this I thought I saw a thicker border on the bottom of the button in the hover state, which is why I added { box-shadow: 0px 1px #1BBCBF; }. Looking at it now, though, I don't see any change when I click/ unclick the little eye button thing next to it. What am I missing here? 

I won't change anything in the code yet since I am clearly confused :) Thanks for your help!
